# Generated by Django 3.1.3 on 2020-11-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecname', models.CharField(default='', max_length=50)),
                ('locname', models.CharField(default='', max_length=50)),
                ('opsticket', models.CharField(default='19191919', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(default='', max_length=50)),
                ('longitude', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
