# Generated by Django 3.1.3 on 2020-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thcore', '0002_mark_inorout'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='empname',
            field=models.CharField(default=1, max_length=50, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='opsticket',
            field=models.CharField(default='', max_length=10),
        ),
    ]
