# Generated by Django 3.1.3 on 2020-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thcore', '0003_auto_20201204_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='empname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
